### Comprobar salto a enter_msisdn
GET http://localhost:8080/{{country}}/{{pagePath}}/msisdn?cid={{cid}}&tariff={{tariff}}&msisdn={{msisdn}}

### Notification
POST http://localhost:8081/notification/af
Content-Type: application/json

{
  "id": 1,
  "subscription_id": 1,
  "id_campaing": 1,
  "state": "inactive",
  "offer_id": 1,
  "offer_name": "Gametime day",
  "charged": 1,
  "msisdn": "666777888"
}